### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/performance-analyzer-rca#139]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable / method / class name.
- Replace "master" in REST API request parameter and response
- Replace OpenSearch REST API that contains "master" with the provided inclusive REST API
such as replacing [GET _cat/master](https://github.com/opensearch-project/performance-analyzer-rca/blob/1.2.3.0/src/main/java/org/opensearch/performanceanalyzer/rca/RcaControllerHelper.java#L55) with "GET _cat/cluster_manager"

Specifically,
The "master" terminology in the REST API will be exposed to the user, so should be prioritized.
Impacted REST API: `GET <endpoint>:9600/_plugins/_performanceanalyzer/metrics`
Document: https://opensearch.org/docs/1.3/monitoring-plugins/pa/api/
Detail: Names of 3 [Performance Analyzer metrics](https://opensearch.org/docs/latest/monitoring-plugins/pa/reference/) can be contained in an optional parameter of the API request, and a field of the API response: Master_PendingQueueSize  , Master_Task_Queue_Time , Master_Task_Run_Time . 

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by sruti1312** [comment]
PA does not call any deprecated API's in core or another plugin.

**Comment by anasalkouz** [comment]
@sruti1312 @kaushalmahi12
Is there any remaining effort in this task? if not, please close the issue

**Comment by anasalkouz** [comment]
@kaushalmahi12 Can you close this? if we have everything merged.
