### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/performance-analyzer-rca#199]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @kkhatua @sruti1312 can you please post an update and make the necessary changes to align with core branching strategy.
Thank you
@dblock @bbarani @CEHENKLE

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by bbarani** [comment]
@sgup432 I have re-tagged this issue to 2.4.0 version.

**Comment by kkhatua** [comment]
@dzane17  can you follow the same actions taken for the PA plugin (https://github.com/opensearch-project/performance-analyzer/issues/241)  and update the [checklist](https://github.com/opensearch-project/performance-analyzer-rca/issues/199#issuecomment-1262538598)

**Comment by kiranprakash154** [comment]
Closing this issue out since 2.4.0 is scheduled to be released soon and manifest has 2.4.0 set - [link](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.4.0/opensearch-2.4.0.yml#L51)
