### ISSUE TITLE
[FEATURE] Increase Code Coverage for Reader

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/performance-analyzer-rca#284]
**Is your feature request related to a problem?**
Improve the code coverage for the [metric reader](https://github.com/opensearch-project/performance-analyzer-rca/tree/main/src/test/java/org/opensearch/performanceanalyzer/reader) subcomponent.  We have seen bugs, see https://github.com/opensearch-project/performance-analyzer-rca/issues/251, which could have been easily detected with reader Unit Tests.

 Currently, the `performance-analyzer-rca` repository is at 71% unit test code coverage.
```
@@             Coverage Diff              @@
##               main     #276      +/-   ##
============================================
- Coverage     71.54%   71.51%   -0.04%     
+ Complexity     2987     2985       -2     
============================================
  Files           380      380              
  Lines         18984    18984              
  Branches       1463     1463              
============================================
- Hits          13583    13576       -7     
- Misses         4805     4810       +5     
- Partials        596      598       +2     
````

**What solution would you like?**
Add unit test for all the metric read and parse logic within Reader.

**Do you have any additional context?**

**Comment by Tjofil** [comment]
Did some more investigating. We can activate certain execution paths by adding just a few tests, usually metrics emitting that we do not emit right now with our unit tests and by testing some smaller utility classes like FileHandler etc. This brings us up to around 89-90% line coverage for the reader package.

The rest of the lines that we are not hitting are mostly getters, setters, delegating constructors - smaller portion and some, by the looks of it, dead code - larger portion.

Some functions that are not being called from anywhere, or are being called from other dead code and that we do not hit with our tests (I might be missing something, if that's the case we can work on tests that cover them) :

https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/reader/MetricProperties.java#L325

https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/reader/MetricProperties.java#L203

https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/reader/MetricProperties.java#L141

from the MetricProperties class. They alone contribute hundreds of lines to the statistics.

There are some other dead code functions like `putMetrics` methods for Snapshot classes, that we can put into tests easily.
