### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer-rca#293]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
You have the `performance analyzer` team with 13 members that have maintain access to this repo and a `plugins` team with 8 members that has admin access. Only folks listed in MAINTAINERS/CODEOWNERS need to have maintain access, and groups don't support external collaborators and therefore should be removed except for `admin`. Please work with an admin to remove the group, and add individuals.

**Comment by kkhatua** [comment]
@dblock there is a `Maintainer` tag in the team. Shouldn't that be what is reflected in the `CODEOWNERS` and `MAINTAINERS`? 
The `performance analyzer` team has folks with committer access so as to reduce the load and improving response time; and we are following the requisite review process of minimum of 2 votes.
(Tagging @praveensameneni )

**Comment by dblock** [comment]
The permissions are incorrect. Please work with an admin to remove the team that has maintain access and add individuals from MAINTAINERS.
![Screenshot 2023-04-04 at 12 12 52 PM](https://user-images.githubusercontent.com/542335/229853394-e264cd51-620b-4c21-9d7f-f65a398a3c7d.png)

**Comment by gaiksaya** [comment]
Permissions updated for this repo as per the maintainers list:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/61760125/232607499-bf4c77d4-2f64-40a8-a090-2f799ad11b67.png">

@praveensameneni @khushbr Please verify!

Thanks!

**Comment by dblock** [comment]
Verified, thx.
