### ISSUE TITLE
[FEATURE] Add health and operational metrics

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/performance-analyzer-rca#311]
**Is your feature request related to a problem?**
We have health and operational metrics present at: 
1. https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java 
2. https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java
3. https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerThreads.java#L18

However, this metric is not exhaustive and at some places, lacks instrumentation. 

**What solution would you like?**
We need to re-visit these metrics and check if all the metrics are instrumented, tested and add any missing metrics we identify for the health of each individual component.

**Comment by Tjofil** [comment]
I've run a round of analysis of the above mentioned metrics.

It is good to note that these metric or how are they internally called `MeasurementSet` are used in variety of different scenarios.
I.e. metrics from point 1. cover more general error scenarios that our framework can run into, metrics from point 2. cover bootstrapping related events, error enumeration types for all thread types running inside the 'PA' app as well as wide variety of logging related to sizes/numbers/logs and other metadata for the processes run inside the `PA` agent, third ones are just packed thread specific exception enums from point 2, and are assigned to each thread type.
What they all have in common is that they are written to in-memory maps managed by Aggregators, for few different reasons:

- To have useful logging and monitoring material for RCA and other parts of the `PA` agent in period where standard metrics written (by `PA` plugin's `Writer`) are unavailable, i.e. awaiting their read-aggregate-persist lifecycle to complete, or when they are not available at the start of the process or during any `Opensearch` process related failures.
- Providing metadata for on-disk structures and their respective events as well all the metric reading/writing/persisting processes.
- Allow for accessible information about certain problems/events that are to be handled by for example, `ExceptionHandlingThread`.

Going over the points listed from issue description:
1. From [first 4 metrics](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L15-L21) only the `CONFIG_DIR_NOT_FOUND` is not instrumented inside this repo, but `PA` controller plugin uses it to [report config directory errors](https://github.com/opensearch-project/performance-analyzer/blob/81d019af51a62d42592905cffc51f9c77cb8aaac/src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java#L333) inside `PA` repo. 
[Next 4](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L27-L42) are very general and report exceptions thrown from most generic and widely invoked methods of the system, gather, persist, operate and compute, and seem correctly instrumented for their respective methods.
Then there is [`READER_METRICSDB_ACCESS_ERRORS`](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L45) which is correctly used to report multiple problems related to accessing `MetricsDB` disk files.
[Rest of the metrics from this category](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L47-L64) each represent a runtime error produced by a collector thread - `Opensearch` process specific collectors. As these metrics currently reside in `PerformanceAnalyzer` repo, they are correctly used for error reporting like i.e. [ClusterManagerThrottlingCollector](https://github.com/opensearch-project/performance-analyzer/blob/e140e73bbefd778610a1187e96ee4d46f1dad608/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerThrottlingMetricsCollector.java#L89), except for [CLUSTER_MANAGER_CLUSTER_UPDATE_STATS_COLLECTOR_ERROR](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L57) which is not used anywhere nor does it correspond to a certain collector. If we take a look at other collector we can see that some of them do not report any kind of errors to the stat map, but only log their errors, like [ClusterManagerServiceMetrics](https://github.com/opensearch-project/performance-analyzer/blob/e140e73bbefd778610a1187e96ee4d46f1dad608/src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java#L100). We should consider removing the one for a non-existent collector and adding metrics for the existing ones.

2.  For this category starting from the top, [metrics describing the number of RCA agent threads started/ended](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java#L22-L25), followed by [exception enums for unexpected stops of various non-collector and non-reader threads](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java#L34-L49), [Time duration that it took `ReaderMetricProcessor` to read and process all the written events](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java#L53), [`RCAScheduler` restart event](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java#L62), and all of them appear to be used correctly to report their appropriate events, errors etc..
After them come [different `MeasurementSet` metrics](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java#L66-L157) identifying various metadata metrics related to on-disk files, batch put, HTTP errors and events as well as some processing times, these are well documented with comments and are used at least once in their respective scenarios.

3. As mentioned in intro paragraph, these are not really the same metrics as the ones from point 1. and point 2. but wrapper enums for a subset of metrics in point 2. They identify utility thread types spawned by `PA Agent` and use the error types from point 2 to mark occurrences of thread errors, so they can be counted and handled, like [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/8214254d5c1e3724200732ad9f368886fc9f58de/src/main/java/org/opensearch/performanceanalyzer/threads/ThreadProvider.java#L52) - each Thread type is going to have it's own error type bound to it by `PerformanceAnalyzerThread` enum.

**Comment by khushbr** [comment]
Thank you for the analysis, Filip. 


As I understand, the Exception Aggregation and Logging component is common to both PA and RCA and currently residing in RCA repo. As next step, we should extract this common code to the common library proposed in https://github.com/opensearch-project/performance-analyzer-rca/issues/307 


Meanwhile, the metrics should cover all the Performance Analyzer Agent App bootstrap failure scenarios(see [this](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java#L139)) and Collectors failures.

**Comment by Tjofil** [comment]
@khushbr 
Looked more into it and found out that [`ErrorHandlingThread`'s starting position](https://github.com/opensearch-project/performance-analyzer-rca/blob/8214254d5c1e3724200732ad9f368886fc9f58de/src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java#L132) is fine. The thread uses `exceptionQueue` for all of it's communication and handling. Only other entities that have access to this queue are threads that are started through [`createThreadForRunnable`](https://github.com/opensearch-project/performance-analyzer-rca/blob/8214254d5c1e3724200732ad9f368886fc9f58de/src/main/java/org/opensearch/performanceanalyzer/threads/ThreadProvider.java#L31) function and these are only 4 PA key threads started after `ErrorHandlingThread`: `Reader`, `GrpcServer`, `WebServer` and `RcaTopLevel` threads.

Moreover, `ErrorHandlingThread`'s job currently comes down to updating the static map like all other basic try-catch constructs spread around PA app - the four aforementioned threads, in case of unexpected errors (note that some of its errors are handled on-site by the thread itself), populate the queue with information and exception types provided from enums discussed in issue description and comments. `ErrorHandlingThread` unblocks on non-empty queue and [updates the stat map](https://github.com/opensearch-project/performance-analyzer-rca/blob/8214254d5c1e3724200732ad9f368886fc9f58de/src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java#L216).
This is pretty basic handling but its intentions are for it to be expanded like described in comment [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/8214254d5c1e3724200732ad9f368886fc9f58de/src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java#L211). It would be beneficial adding these functionalities in the future.
