### ISSUE TITLE
[BUG] Sum is used when calculating and reporting hot shard metrics

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/performance-analyzer-rca#360]
**What is the bug?**
We are [using the sum of all data points in the sliding window](https://github.com/opensearch-project/performance-analyzer-rca/blob/a6edfbf6d3d71511e89c8c2d418f1582cbeb5407/src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hotshard/HotShardClusterRca.java#L85) to calculate the value of hot shard metrics and reporting it as the final results. This is inconsistent with the threshold which is set for each individual datapoint instead of the sum.

Ideally we should use `median` or `mean` to calculate the hot shards and report it as the final results.

**How can one reproduce the bug?**
1. Enable HotShardClusterRca on a OpenSearch Domain with loads
2. Check the HotShardClusterRca output with
```
curl -s --url localhost:9650/_plugins/_performanceanalyzer/rca\?name=HotShardClusterRca -XGET
```

**What is the expected behavior?**
The HotShardClusterRca results should be in the same order of magnitude as the threshold.

**Comment by Tjofil** [comment]
Thank you @ansjcy for submitting these findings.

I looked into this more in detail and I might have a bit different explanation:
It is true that values are not getting averaged and only getting summarized but [the way the `HotShard` RCAs are configured by default](https://github.com/opensearch-project/performance-analyzer-rca/blob/066509d4936e20d7a5154cb52ad35a931704c7d2/src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java#L514-L532) implies that it doesn't matter when it comes order of magnitude of the results. Let me explain - `HotShardRCA` is only sending non-empty FlowUnits to the `HotShardClusterRCA` once every minute, and the `HotShardClusterRCA` is generating reports and clearing all the previous data also once every minute. This means that no combination of Index, Node, Shard can occur twice inside the same `HotShardClusterRCA` window, regardless of the aligning of different RCA windows that can potentially occur. This means no addition is really happening at all, thus creating no difference if the values are getting averaged or not. I've tried several runs to confirm this and it was as I expected, please correct me if I overlooked something.

The thresholds on the other hand may not be ideally set up as the expected values tend to vary a lot depending on the cluster configuration and the machines the OS is running on. I suggest we run benchmarks on most common cluster configurations used in production and create a table of suggested thresholds for each configuration.
