### ISSUE TITLE
[FEATURE] SearchBackPressure Reader

### ISSUE THREAD

**Issue by CoderJeffrey** [opensearch-project/performance-analyzer-rca#424]
**Is your feature request related to a problem?**
For the Pull & Request https://github.com/opensearch-project/performance-analyzer/pull/483 for PA plugin, the feature of gathering Search Back Pressure related Metrics has been introduced, however, the RCA part has not been made to show the metrics in shared memory folder to users (e.g. when using curl)

**What solution would you like?**
The RCA framework should add a new reader to consume the incoming data.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**

**Comment by khushbr** [comment]
- All the relevant changes are merged, closing this issue.
