### ISSUE TITLE
[FEATURE] REST Layer UTs

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/performance-analyzer-rca#430]
**Is your feature request related to a problem?**
RCA Agent contains a web server which is used for servicing `_metrics` and `_rca` API GET and POST requests.  Add Unit tests for the REST layer covering following scenarios:
1. Add UTs for [QueryRcaRequestHandler.java](https://github.com/opensearch-project/performance-analyzer-rca/blob/efa0fa0a109c3edb2be4e32b9b5536f5f4bb9dad/src/main/java/org/opensearch/performanceanalyzer/rest/QueryRcaRequestHandler.java) - checking for  response body and status code 
2. Within `QueryRcaRequestHandlerTest`, add test for special scenaior:  If a Cluster and its Node Level RCA is muted, say `HotShardRca, HotShardClusterRca`, the following API calls should return empty response. 
```
GET localhost:9600/_plugins/_performanceanalyzer/rca
GET localhost:9600/_plugins/_performanceanalyzer/rca?name=HotShardClusterRca
```
3. Add UTs for [QueryActionRequestHandler](https://github.com/opensearch-project/performance-analyzer-rca/blob/efa0fa0a109c3edb2be4e32b9b5536f5f4bb9dad/src/main/java/org/opensearch/performanceanalyzer/rest/QueryActionRequestHandler.java) 

**Do you have any additional context?**
Current REST Layer code: https://github.com/opensearch-project/performance-analyzer-rca/tree/efa0fa0a109c3edb2be4e32b9b5536f5f4bb9dad/src/test/java/org/opensearch/performanceanalyzer/rest

**Comment by Tjofil** [comment]
Adding for context, looks like standard cluster level RCA's are not treated the same as local temperature RCA's when it comes to muted RCA configuration.
Rest handler for RCA multiplexes between these two and delegates the processing to their respective handles. While handle for [local temperature RCA's checks for muted lists and returns `BAD_REQUEST`](https://github.com/opensearch-project/performance-analyzer-rca/blob/efa0fa0a109c3edb2be4e32b9b5536f5f4bb9dad/src/main/java/org/opensearch/performanceanalyzer/rest/QueryRcaRequestHandler.java#L97) (from the perspective of code at least, still has to be tested if it works correctly) and the cluster level RCA handle just ignores this check and proceeds with querying the DB for RCA findings. This will have to be implemented uniformly for both cases.
