### ISSUE TITLE
[BUG] Build Process failed for the discrepency of log4j version

### ISSUE THREAD

**Issue by CoderJeffrey** [opensearch-project/performance-analyzer-rca#460]
**What is the bug?**
The build process stuck on the "Update SHA" step due to the following error
```
> Task :updateShas FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateShas'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Conflict(s) found for the following module(s):
       - org.apache.logging.log4j:log4j-api between versions 2.20.0 and 2.17.1
       - org.apache.logging.log4j:log4j-core between versions 2.20.0 and 2.17.1
     Run with:
         --scan or
         :dependencyInsight --configuration runtimeClasspath --dependency org.apache.logging.log4j:log4j-api
     to get more insight on how to solve the conflict.
```

**How can one reproduce the bug?**
1. Trigger the build process for one-line code change.

**What is the expected behavior?**
Build Process should be able to pass.
This PR that involves minimal code change also failed: https://github.com/opensearch-project/performance-analyzer-rca/pull/454

**What is your host/environment?**
 - JDK 17

**Do you have any additional context?**
The build process runs successfully in local environment.

**Comment by khushbr** [comment]
Fixed at https://github.com/opensearch-project/performance-analyzer-commons/commit/0197ef09386c5517073a33268db0fc1612e9c1a8
