### ISSUE TITLE
[BUG] Upgrade gradle to 8.1.1 for performance-analyzer-rca 2.9 version

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/performance-analyzer-rca#464]
**what is the issue**
There's a bug in the shadow plugin which caused build failures with gradle version 7.6.1. ([related issue](https://github.com/opensearch-project/opensearch-hadoop/issues/213))

Core OpenSearch is using gradle version 8.1.1: https://github.com/opensearch-project/OpenSearch/blob/2.9/gradle/wrapper/gradle-wrapper.properties
We should upgrade the gradle version for our package.

**What is your host/environment?**
 - OS: [Linux]
 - Version [2.9.0]
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
Gradle was upgraded to 8.5.
