### ISSUE TITLE
PR check CI failing for unrelated unit tests

### ISSUE THREAD

**Issue by mch2** [opensearch-project/performance-analyzer-rca#49]
PR check CI is failing for tests unrelated to changes and multiple commits have bypassed this check.

669 tests completed, 87 failed

This is the earliest run that I can see with this error, runs before this were timing out. https://github.com/opensearch-project/performance-analyzer-rca/actions/runs/1083071491

**Comment by dblock** [comment]
This is more than the spotbugs issue, isn't it? Why am I not seeing these failures in recent CI runs? @mch2

**Comment by mch2** [comment]
This looks like it was fixed with #52
