### ISSUE TITLE
[BUG] Performance-Analyzer-rca Distribution build failures

### ISSUE THREAD

**Issue by atharvasharma61** [opensearch-project/performance-analyzer-rca#530]
**What is the bug?**
There is [a bug in gradle](https://github.com/gradle/gradle/issues/24390) Versions prior to 7.6.2 (?) which failed to handle multi-release jar files (ie with multiple binaries built with different Java versions in them).
The jackson dependency is such a jar file that caused build failures. Issue was fixed post gradle version 8.4

**How can one reproduce the bug?**
```
./gradlew build
```

**What is the expected behavior?**
Build should succeed

**What is your host/environment?**
 - OS: MacOS

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
I believe we've upgraded to newer versions of Gradle since. Closing. Reopen if this is still a problem?

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)
