### ISSUE TITLE
[BUG] Tests take hours, reduce for CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer-rca#57]
**What is the bug?**

Successful runs take ~2 hours, and many CI jobs time out. Makes fast iterations very difficult.
https://github.com/opensearch-project/performance-analyzer-rca/actions/workflows/gradle.yml 
Every `testActionBuilder` call runs for about 3 minutes.  

As part of https://github.com/opensearch-project/performance-analyzer-rca/pull/55, slow tests were disabled in https://github.com/opensearch-project/performance-analyzer-rca/pull/55/commits/b6e510cc683d6e222ac6be93302603323bc960a8, but that's obviously not a viable long term solution.

**What is the expected behavior?**

Tests in CI need to complete reliably in minutes.

If the tests themselves can't be fixed, start by extracting integration tests into one or more separate workflows that can be executed in parallel or outside of CI for PRs (e.g. in infra Jenkins daily).

**Comment by aditjind** [comment]
Long Standing Problem in PA and RCA, needs to be prioritized.

**Comment by sruti1312** [comment]
Long running integration tests are moved to separate workflow that is executed in parallel.
