### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/performance-analyzer-rca#59]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by sruti1312** [comment]
Backward compatibility tests are added on the ```performance-analyzer``` plugin side. 
https://github.com/opensearch-project/performance-analyzer/pull/69

PA Reader process or ```performance-analyzer-rca ``` runs as a separate process independent of opensearch. Hence BWC tests cannot be added for them.
