### ISSUE TITLE
[BUG] Maven central publication fails (Missing: no javadoc jar found in folder '/org/opensearch/performanceanalyzer-rca/1.1.0.0')

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer-rca#79]
**What is the bug?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/699, in trying to promote maven artifacts for 1.1 to Maven central we're seeing.

```
Missing: no javadoc jar found in folder '/org/opensearch/performanceanalyzer-rca/1.1.0.0
```

Should we be trying to release maven artifacts for performanceanalyzer-rca at all? If not, we need to make sure nothing is published to maven during build. Otherwise fix the missing Javadoc JAR.

**Comment by dblock** [comment]
Is this resolved @sruti1312 ?

**Comment by sruti1312** [comment]
Performance Analyzer RCA jar is bundled with the PA plugin jar (as a dependency) and hence can be skipped from publishing to maven central. @dblock Any thoughts?

**Comment by guillaume-alvarez** [comment]
This is causing issues when trying to build the performance analyzer plugin: it tries to load Performance Analyzer RCA artifacts during gradle build.

Shouldn't it at least be published to apache or sonatype repo?
