### ISSUE TITLE
[BUG] Missing: no sources jar found in folder '/org/opensearch/performanceanalyzer-rca/1.1.0.0'

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer-rca#81]
**What is the bug?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/699. In trying to promote to maven central we see the following failure:

```
Missing: no sources jar found in folder '/org/opensearch/performanceanalyzer-rca/1.1.0.0'
-- | --

**Comment by dblock** [comment]
Is this resolved @sruti1312 ?

**Comment by sruti1312** [comment]
Performance Analyzer RCA jar is bundled with the PA plugin jar (as a dependency) and hence can be skipped from publishing to maven central.
