### ISSUE TITLE
[BUG] Missing 1.1.0.0 tag

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer-rca#85]
**What is the bug?**

The repo is missing a 1.1.0.0 release tag. 

**Do you have any additional context?**

Trying to lock https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.1.0/opensearch-1.1.0.yml to a stable ref.

**Comment by sruti1312** [comment]
Created the 1.1.0.0 release tag https://github.com/opensearch-project/performance-analyzer-rca/tree/1.1.0.0
